version: "3"

services:
  nginx:
    container_name: jakobschoepe/nginx:amd64-1.22.0
    image: amd64/nginx:1.22.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
      
  certbot:
    container_name: jakobschoepe/certbot:amd64-1.27.0
    image: certbot/certbot:amd64-v1.27.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
     
  shiny:
    container_name: shiny
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
      - 3838
    volumes:
      - ./app:/srv/shiny-server
      - ./logs:/var/log
