version: "3"

services:
  nginx:
    container_name: nginx
    image: amd64/nginx:1.22.0
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/:ro
      - ./nginx:/etc/nginx/conf.d/:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  
      
  certbot:
    container_name: certbot
    image: certbot/certbot:amd64-v1.27.0
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
     
  shiny:
    container_name: shiny
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    expose:
      - 3838
    volumes:
      - ./app:/srv/shiny-server
      - ./logs:/var/log
